### ISSUE TITLE
Bug with the bottom of the outline

### ISSUE THREAD

**Issue by milioner1** [Caedilla/Masque_Raeli#1]
![image](https://user-images.githubusercontent.com/58864610/74597927-5e7c8700-5070-11ea-83f6-82b681f0f5c2.png)

As is shown in the photo above, there seems to be a bug with the bottom line of the outline, when it comes to debuffs. It fails to show.

Hopefully you can fix this.

Also, I was wondering if there was a way to eliminate the glossy quality from the debuff icons.

Thanks in advance!

Any news on updating this to include 8.3 icons?

**Comment by Caedilla** [comment]
That occurs due to imperfect scaling, there's not much I can do about it, especially since this is just a masque skin. You should try adjusting your UI scale, or the size of the icons. 

I'm not really sure what you mean with glossy part - there is an optional gloss, and that's controlled in Masque's settings.

Finally, I'm not sure what you mean by 8.3 icons, this only supports whatever Masque itself supports.
